### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by NicoleEtLui** [geekskai/react-network-detect#3]
Hi, thx again for your package !

I have trouble running it in a `nextjs` app. 

* setup: 

````
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-network-detect": "^1.0.7",
    "next": "12.1.6",
````

* problems

I have to add `type: modules` to your `package.json`
 or i get 
 
 `SyntaxError: Cannot use import statement outside a module`

and when i try to use `useOnlineEffect`

```
import React from "react";
import { useOnlineEffect } from "react-network-detect";

export const MyComponent
const isOnline = useOnlineEffect();

...

```

I get `TypeError: Cannot read properties of null (reading 'useState')`

Let me know if i can give you more info

**Comment by geekskai** [comment]
Thank you very much for being able to use this package, could you please give the demo link of codesandbox?

**Comment by geekskai** [comment]
@NicoleEtLui  you can look at this  https://codesandbox.io/s/adoring-goldwasser-9utfxm?file=/pages/index.js

**Comment by NicoleEtLui** [comment]
It seems to work in 1.0.11 indeed ! Thx for the quick answer !
